# todo: add config file and assigne based on it and label
name: AutoAssigner

on:
  issues:
    types: [opened]
    

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign labels
        uses: actions/github-script@v2
        with:
          github-token: ${{ secrets.DPRO_TOKEN }}
          script: |
            const labels = []
            const assignees = [context.actor]
            const developers = ['dmitry-prohorov']
            const qa = ['']
            if (developers.includes(context.actor)) {
              labels.push('development')
            }
            if (qa.includes(context.actor)) {
              assignees.push('dmitry-prohorov')
            }
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              assignees: assignees.concat(context.payload.issue.assignees.map(assignee => assignee.login)).filter((e,i,a) => e && a.indexOf(e) === i),
              labels: labels.concat(context.payload.issue.labels).filter((e,i,a) => e && a.indexOf(e) === i)
            }
            console.log(request)
            await github.issues.update(request)
