# todo: add config file and assigne based on it and label
name: AutoAssigner

on:
  issues:
    types: [opened]
    

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign labels
        uses: actions/github-script@v2
        with:
          script: |
            console.log(context)
            const labels = [];
            const developers = ['dmitry-prohorov']
            if (developers.includes(context.actor)) {
              labels.push('development');
            }
            await github.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.nubmer,
              assignees: [context.actor].concat(context.payload.issue.assignees).filter((e,i,a) => e && a.indexOf(e) === i),
              labels: labels.concat(context.payload.issue.labels).filter((e,i,a) => e && a.indexOf(e) === i)
            })
