name: Coverage
on:
  workflow_dispatch:
    inputs:
      org:
        required: true
        description: Org name.
        default: 'origin'
      assignees:
        required: false
        description: Comma-separated list of assignee to assign in fail test issue
      issue_prefix:
        required: false
        description: An issue prefix to create
      labels:
        required: false
        description: Comma-separated list of labels to add
      issue_number:
        required: false
        description: Id(number) ussue to update
        

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.GITHUB_REF }}
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '13.x'

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Salesforce CLI
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          npm install sfdx-cli
          node_modules/sfdx-cli/bin/run --version
          node_modules/sfdx-cli/bin/run plugins --core

      - name: Convert inputs
        id: secrets
        env:
          ORG_NAME: ${{ github.event.inputs.org }}
        run: |
          USERNAME="${ORG_NAME^^}_USERNAME"
          echo ::set-output name=username::$USERNAME

      - name: Setup job environment
        env:
          USERNAME: ${{ steps.secrets.outputs.username }}
        run: | 
          echo ::set-env name=ORG_USERNAME::${{ secrets[env.USERNAME] }}

      - name: Authenticate Org
        env:
          SALESFORCE_JWT_SECRET_KEY: ${{ secrets.ORIGIN_JWT_SECRET_KEY }}
        run: |
          echo "${SALESFORCE_JWT_SECRET_KEY}" > server.key
          echo "${ORG_USERNAME}"
          node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid ${{ secrets.ORIGIN_CONSUMER_KEY }} --jwtkeyfile server.key --username ${ORG_USERNAME} --setdefaultdevhubusername -a currentorg

      - name: Run all org tests
        continue-on-error: true
        run: |
          mkdir test-results
          # SFDX_IMPROVED_CODE_COVERAGE='true' node_modules/sfdx-cli/bin/run force:apex:test:run -d test-results -r json -c -u currentorg
  
      - name: Get test run summary
        id: result
        uses: actions/github-script@v2
        with:
          script: |
            const fs = require('fs')
            const path = require('path')
            const testRunId = '123'
            // await fs.promises.readFile(path.resolve('test-results', 'test-run-id.txt'), 'utf8')
            const result = { summary: { test: 123 } }
            // JSON.parse(await fs.promises.readFile(path.resolve('test-results', `test-result-${testRunId}.json`), 'utf8'))
            console.log('------------SUMMARY--------------')
            console.log(result.summary)
            
            if (context.payload.inputs.issue_number) {
              await github.issues.createComment({ 
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: `${context.payload.inputs.issue_number}`,
                body: JSON.stringify(result.summary, null, '  ')
              })
            }

            if (result.summary.failing > 0) {
              const code = '```';
              const fails = result.tests.filter(test => test.Outcome === 'Fail')
              console.log('------------FAILS--------------')
              fails.forEach(test => {
                console.group(`Method: ${test.FullName}`);
                console.group(`Trace:\n${test.StackTrace}`);
                console.groupEnd();
                console.log(`Message: ${test.Message}`);
                console.groupEnd();
              })
              const issueFails = fails.map(test => {
                return `- [ ] ${test.FullName}`
              }).join('\n')
              const logUrl = `${context.payload.repository.html_url}/actions/runs/${process.env.GITHUB_RUN_ID}`
              const request = {
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `Auto-generated message by ${context.workflow}(${context.eventName}).\n\n\n### Summary\n${code}javascript\n${JSON.stringify(result.summary, null, '  ')}\n${code}\n\n### Fails:\n${issueFails}\n\n### [Details](${logUrl})`,
              }
              if (context.payload.inputs.issue_number) {
                await github.issues.createComment({ ...request, issue_number: context.payload.inputs.issue_number})
              } else {
                await github.issues.create({
                  ...request,
                  title: `[${context.payload.inputs.issue_prefix || 'Test Coverage'}]: Fix tests in branch "${context.ref}".`,
                  assignees: (context.payload.inputs.assignees || context.actor).split(','),
                  labels: ['automation', 'development', 'bug'].concat((context.payload.inputs.labels || '').split(',')).filter((e,i,a) => e && a.indexOf(e) === i)
                })
              }
            }
        


