# This is a basic workflow to help you get started with Actions

name: PullRequestPassRateCI

# Controls when the workflow will run
on:
  pull_request_review:
    types: [submitted]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  unapproved:
    if: github.event.review.state == 'CHANGES_REQUESTED'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Context
        uses: actions/github-script@v3
        with:
          script: |
            console.log(`Context: ${JSON.stringify(context)}`)
      - name: Github
        uses: actions/github-script@v3
        with:
          script: |
            console.log(`Github Event: ${JSON.stringify(github.event)}`)
            console.log(`Github Event Review: ${JSON.stringify(github.event.review)}`)
