# This is a basic workflow to help you get started with Actions

name: PullRequests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]
    types: [synchronize, opened, reopened, ready_for_review]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
     
  # This workflow contains a single job called "build"
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Context
      uses: actions/github-script@v2
      with:
        script: |
          console.log(context)
          console.log(context.payload.pull_request.body)
          
          function getIssueNumber(body) {
            const matches = body.match(/ISSUE TO RESOLVE: #([\d]+)/g)
            if (!matches) return null
            return matches[0].split('#')[1]
          }
          const issue_number = getIssueNumber(context.payload.pull_request.body)
          const request = {
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Fix please test body'
          }
          if (issue_number) {
            await github.issues.createComment({ ...request, issue_number })
          } else {
            await github.issues.create({
              ...request,
              title: `['Test Coverage']: Fix tests in branch "${context.ref}".`,
              assignees: [context.actor],
              labels: ['bug']
            })
          }
    - name: Skip if draft
      if: github.event.pull_request.draft == false
      run: echo "PR not draft"
